// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with my Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuclbC8ZMkpJpy4jNTaDH8q4auEU1WLcM',
    appId: '1:75858215020:web:994c9dc106d8627e475849',
    messagingSenderId: '75858215020',
    projectId: 'afa-chat-17bf8',
    authDomain: 'afa-chat-17bf8.firebaseapp.com',
    storageBucket: 'afa-chat-17bf8.firebasestorage.app',
    measurementId: 'G-D2BEJS9TK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1i5XtyEDHs7489y5a0yxN1oPPdPAYod0',
    appId: '1:75858215020:android:c6269c0067627bc8475849',
    messagingSenderId: '75858215020',
    projectId: 'afa-chat-17bf8',
    storageBucket: 'afa-chat-17bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXjnhnHsEuMqlUMMld_KsoQzW4DQKugx0',
    appId: '1:75858215020:ios:7503e79741103106475849',
    messagingSenderId: '75858215020',
    projectId: 'afa-chat-17bf8',
    storageBucket: 'afa-chat-17bf8.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXjnhnHsEuMqlUMMld_KsoQzW4DQKugx0',
    appId: '1:75858215020:ios:7503e79741103106475849',
    messagingSenderId: '75858215020',
    projectId: 'afa-chat-17bf8',
    storageBucket: 'afa-chat-17bf8.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuclbC8ZMkpJpy4jNTaDH8q4auEU1WLcM',
    appId: '1:75858215020:web:1c20c29fcbf282d9475849',
    messagingSenderId: '75858215020',
    projectId: 'afa-chat-17bf8',
    authDomain: 'afa-chat-17bf8.firebaseapp.com',
    storageBucket: 'afa-chat-17bf8.firebasestorage.app',
    measurementId: 'G-WJ7EXN6XL0',
  );
}
